Repository sweIhm-ws2018-19/skillproject-fr-11, pull requests merged in 2018-11, with the labels that each got.

#61 Feature/hs 54 gesamtdatenmodell
  src/main/java/hypershop/model/IngredientAmount.java
  src/main/java/hypershop/model/Recipe.java
  src/main/java/hypershop/model/ShoppingList.java
  src/main/java/hypershop/model/Unit.java
  src/main/java/hypershop/model/UnitConversion.java
  src/main/java/hypershop/service/IngredientAmountService.java
  src/main/java/hypershop/service/ShoppingListService.java
  src/main/java/hypershop/service/UnitConversionService.java
Labels: feature

#62 rename color project + add prototype code
  pom.xml
  src/edu/hm/cs/seng/hypershop/Constants.java
  src/edu/hm/cs/seng/hypershop/HypershopStreamHandler.java
  src/edu/hm/cs/seng/hypershop/SpeechTextConstants.java
  src/edu/hm/cs/seng/hypershop/handlers/AddIngredientIntentHandler.java
  src/edu/hm/cs/seng/hypershop/handlers/CancelandStopIntentHandler.java
  src/edu/hm/cs/seng/hypershop/handlers/FallbackIntentHandler.java
  src/edu/hm/cs/seng/hypershop/handlers/HelpIntentHandler.java
  src/edu/hm/cs/seng/hypershop/handlers/LaunchRequestHandler.java
  src/edu/hm/cs/seng/hypershop/handlers/SessionEndedRequestHandler.java
  src/edu/hm/cs/seng/hypershop/model/IngredientAmount.java
  src/edu/hm/cs/seng/hypershop/model/Recipe.java
  src/edu/hm/cs/seng/hypershop/model/ShoppingList.java
  src/edu/hm/cs/seng/hypershop/model/Unit.java
  src/edu/hm/cs/seng/hypershop/model/UnitConversion.java
  src/edu/hm/cs/seng/hypershop/service/IngredientAmountService.java
  src/edu/hm/cs/seng/hypershop/service/ShoppingListService.java
  src/edu/hm/cs/seng/hypershop/service/UnitConversionService.java
  src/main/java/colorpicker/handlers/MyColorIsIntentHandler.java
  src/main/java/colorpicker/handlers/SessionEndedRequestHandler.java
Labels: feature

#63 feature/hs 56 travis ci setup
  .travis.yml
  README.md
  pom.xml
  src/main/java/edu/hm/cs/seng/hypershop/Constants.java
  src/main/java/edu/hm/cs/seng/hypershop/HypershopStreamHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/SpeechTextConstants.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/AddIngredientIntentHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/CancelandStopIntentHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/FallbackIntentHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/HelpIntentHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/LaunchRequestHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/SessionEndedRequestHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/model/IngredientAmount.java
  src/main/java/edu/hm/cs/seng/hypershop/model/Recipe.java
  src/main/java/edu/hm/cs/seng/hypershop/model/ShoppingList.java
  src/main/java/edu/hm/cs/seng/hypershop/model/Unit.java
  src/main/java/edu/hm/cs/seng/hypershop/model/UnitConversion.java
  src/main/java/edu/hm/cs/seng/hypershop/service/IngredientAmountService.java
  src/main/java/edu/hm/cs/seng/hypershop/service/ShoppingListService.java
  src/main/java/edu/hm/cs/seng/hypershop/service/UnitConversionService.java
  src/test/java/edu/hm/cs/seng/hypershop/model/ShoppingListTest.java
Labels: feature

#65 Feature/hs 58 db setup
  pom.xml
  src/main/java/edu/hm/cs/seng/hypershop/Constants.java
  src/main/java/edu/hm/cs/seng/hypershop/HypershopStreamHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/SpeechTextConstants.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/AddIngredientIntentHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/ListIngredientsIntentHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/model/ShoppingList.java
  src/test/java/edu/hm/cs/seng/hypershop/model/ShoppingListTest.java
Labels: DB, feature

#68 Feature/hs 32 zutat hinzufügen
  pom.xml
  src/main/java/edu/hm/cs/seng/hypershop/SpeechTextConstants.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/AddIngredientIntentHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/handlers/ListIngredientsIntentHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/model/IngredientAmount.java
  src/main/java/edu/hm/cs/seng/hypershop/model/Recipe.java
  src/main/java/edu/hm/cs/seng/hypershop/model/ShoppingList.java
  src/main/java/edu/hm/cs/seng/hypershop/model/Unit.java
  src/main/java/edu/hm/cs/seng/hypershop/service/ModelService.java
  src/main/java/edu/hm/cs/seng/hypershop/service/ShoppingListService.java
  src/main/java/edu/hm/cs/seng/hypershop/service/UnitConversionService.java
  src/test/java/edu/hm/cs/seng/hypershop/model/AddIngredientToShoppingListTest.java
  src/test/java/edu/hm/cs/seng/hypershop/model/RecipeTest.java
  src/test/java/edu/hm/cs/seng/hypershop/model/ShoppingListTest.java
  src/test/java/edu/hm/cs/seng/hypershop/model/addingredients.json
  src/test/java/edu/hm/cs/seng/hypershop/model/addingredients2.json
Labels: feature

#71 add help statement
  src/main/java/edu/hm/cs/seng/hypershop/SpeechTextConstants.java
Labels: feature

#69 Fixed list bug and added handler test for listIngredientsHandler
  .travis.yml
  pom.xml
  src/main/java/edu/hm/cs/seng/hypershop/handlers/ListIngredientsIntentHandler.java
  src/main/java/edu/hm/cs/seng/hypershop/model/ShoppingList.java
  src/main/java/edu/hm/cs/seng/hypershop/service/ModelService.java
  src/main/java/edu/hm/cs/seng/hypershop/service/ShoppingListService.java
  src/resources/addingredients.json
  src/resources/addingredients2.json
  src/resources/cancel.json
  src/resources/help.json
  src/resources/hypershopopen.json
  src/resources/listingredients.json
  src/test/java/edu/hm/cs/seng/hypershop/handlers/AddIngredientToShoppingListTest.java
  src/test/java/edu/hm/cs/seng/hypershop/handlers/CancelandStopIntentHandlerTest.java
  src/test/java/edu/hm/cs/seng/hypershop/handlers/HandlerTestHelper.java
  src/test/java/edu/hm/cs/seng/hypershop/handlers/HelpIntentHandlerTest.java
  src/test/java/edu/hm/cs/seng/hypershop/handlers/LaunchRequestHandlerTest.java
  src/test/java/edu/hm/cs/seng/hypershop/handlers/ListIngredientShoppingListTest.java
  src/test/java/edu/hm/cs/seng/hypershop/model/AddIngredientToShoppingListTest.java
  src/test/java/edu/hm/cs/seng/hypershop/model/ShoppingListTest.java
Labels: bug
